import { describe, it, expect } from 'vitest';
import * as tenantOperationalService from './tenantOperationalService';

const EXPECTED_EXPORTS = [
  "INVITE_CODE_ALPHABET",
  "PLATFORM_PERMISSIONS",
  "approveTenantMember",
  "assignMemberRole",
  "assignRoomContract",
  "autoGenerateKosBilling",
  "bulkCreateTenantUnits",
  "calculateBillingPreview",
  "checkoutKosRoom",
  "createArisanRound",
  "createTenantBillingItem",
  "createTenantExpense",
  "createTenantRole",
  "deleteTenantExpense",
  "deleteTenantRole",
  "drawArisanWinner",
  "enrollArisanParticipants",
  "fetchArisanCandidates",
  "fetchArisanParticipants",
  "fetchArisanRoundBills",
  "fetchArisanRounds",
  "fetchPendingTenantMembers",
  "fetchPlatformPermissions",
  "fetchTenantBillMatrix",
  "fetchTenantBillingItems",
  "fetchTenantDashboardData",
  "fetchTenantDetails",
  "fetchTenantExpenses",
  "fetchTenantInviteCode",
  "fetchTenantMembers",
  "fetchTenantMonthlyFinance",
  "fetchTenantPayments",
  "fetchTenantRoles",
  "fetchTenantRunningBalance",
  "fetchTenantSettingsAudit",
  "fetchTenantUnits",
  "generateArisanRoundBills",
  "generateInviteCode",
  "generateKelasSppBilling",
  "generateTenantBillingItems",
  "getCachedTenantInviteCode",
  "getInviteDetails",
  "getTenantBankAccount",
  "isLegacyQrisEnabled",
  "normalizeBankAccount",
  "payArisanBillManual",
  "pickBankAccountForForm",
  "rejectTenantMember",
  "rejectTenantPayment",
  "requestJoinTenant",
  "resolveCitizenObligationAndUnit",
  "saveInviteCodeWithRetry",
  "saveTenantBankAccount",
  "saveTenantInviteCode",
  "startNewArisanCycle",
  "submitTenantPayment",
  "updateTenantExpense",
  "updateTenantPayment",
  "updateTenantProfileAndSettings",
  "updateTenantRole",
  "verifyTenantPayment",
];

describe('tenantOperationalService Exports Guard (DEBT-1.4)', () => {
  it('harus mengekspor 61 fungsi/konstanta yang sama persis', () => {
    const exportsList = Object.keys(tenantOperationalService).sort();
    expect(exportsList).toEqual(EXPECTED_EXPORTS);
    expect(exportsList.length).toBe(61);
  });
});
